apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb-app
  labels:
    app: airbnb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airbnb-app
  template:
    metadata:
      labels:
        app: airbnb-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: airbnb-app
        image: airbnb-booking-app:metrics
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "airbnbdb"
        - name: DB_USER
          value: "airbnb"
        - name: DB_PASSWORD
          value: "airbnb123"
        livenessProbe:
          httpGet:
            path: /home
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /home
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
